Add a menu driven password editor command

diff --git a/bin/jgy-password-select b/bin/jgy-password-select
--- a/bin/jgy-password-select
+++ b/bin/jgy-password-select
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
+# Find passwords matching the arguments
+# If there is more than one match, show a chooser and print the chosen item
+# If there is one match, print it directly
+
 PREFIX=$HOME/.password-store
 
 die() {
@@ -7,7 +13,7 @@ die() {
   exit 1
 }
 
-jgy_password() {
+jgy_password_select() (
   [[ $# -eq 0 ]] && die "Usage: $0 match [match1 [match2] ...]"
 
   local terms="$(printf '%s.*?' "$@")"
@@ -19,26 +25,25 @@ jgy_password() {
       | sort
   )
 
-  local matches=$(echo "$passwords" | grep -Pi "$terms")
+  local match=$(echo "$passwords" | grep -Pi "$terms")
 
-  [[ -z "$matches" ]] && die "'$@' not found"
+  [[ -z "$match" ]] && die "'$@' not found"
 
-  local count=$(echo "$matches" | wc -l)
+  local count=$(echo "$match" | wc -l)
 
   if [[ $count -eq 1 ]]; then
-    echo "$matches:"
-    pass $matches
+    echo $match
   else
-    local choice=$(echo "$matches" | fzf)
+    local choice=$(echo "$match" | fzf)
     [[ -z "$choice" ]] && exit 1
-    echo "$choice:"
-    pass $choice
+    echo $choice
   fi
-}
+)
 
 if which fzf >/dev/null ; then
-  jgy_password "$@"
+  jgy_password_select "$@"
 else
   die "fzf is not installed"
 fi
+
 exit $?
